### ISSUE TITLE
[Windows][Installation] Setting up notify on Windows through setup.py does not work

### ISSUE THREAD

**Issue by fantinluca** [Zanzibarr/Telegram_Python_Notifier#1]
**Environment**:
- Device: Lenovo Ideapad Flex 5, Windows 11
- Python version: 3.10.4

**Steps**:
1. Create a Telegram bot with BotFather
2. Copy the bot's HTTP API
3. Install the Python package "requests" via terminal
4. Clone the notify repo in any folder through `git clone https://github.com/Zanzibarr/Notify temp_notify_zanz/`
5. Execute `python3 temp_notify_zanz/setup.py`
6. Enter a profile name
7. Enter the HTTP API token of the bot

**Expected result**:
The setup ends successfully.

**Actual result**:
After entering the bot API token, the program ends with the following errors:
```shell
Traceback (most recent call last):
  File "C:\Users\ferra\OneDrive\Desktop\Uni\notify\temp_notify_zanz\setup.py", line 84, in <module>
    notify.write_conf_profile(name=name, token=token)
  File "C:\Users\ferra\OneDrive\Desktop\Uni\notify\temp_notify_zanz\notify.py", line 27, in write_conf_profile
    subprocess.run(["touch", config_path])
  File "C:\Users\ferra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\ferra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ferra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specification
```

**Comment by Zanzibarr** [comment]
Currently the Setup, Update and Uninstall processes are not compatible with Windows.

Windows compatibility will arrive soon.
